version: "3"
services:
  easy-chat-pushjs:
    build:
      context: ./
      args:
        jwt_public_key: "jwtRS256.key.pub" # required for authentication between client and server.
        firebase_sdk_admin_json: "firebase_admin_sdk.json" # firebase authentication (optional) If not needed, set an empty file instead.
    restart: "always"
    ports:
      - "5511:5511" # websocket server
      - "3500:3500" # ZMQ
    environment:
      - "ZMQ_ADDRESS=null" # change to tcp://0.0.0.0:3500 for remote access otherwise it will be accessed only locally.
      - "VERSION=1.0"
      - "FIREBASE_DATABASE_URL=null" # if you want to use firebase push notifications. Check Readme.md.
