FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
ARG jwt_public_key
ARG firebase_sdk_admin_json
RUN apt update && apt install -y tzdata
ENV TZ=UTC/utc
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt install -y git
RUN ls -l /etc/localtime

RUN apt update -y
RUN apt install sudo -y
RUN sudo apt install redis-server -y
RUN sudo apt install curl -y
RUN sudo apt install nodejs npm -y
RUN sudo npm install -g n && sudo n latest
RUN sudo npm install -g yarn
RUN sudo yarn global add pm2
RUN sudo pm2 startup
RUN apt install libzmq3-dev -y
RUN apt install python3 -y
RUN sudo npm install -g zeromq@5
RUN sudo mkdir -p /etc/easy-chat-pushjs/src
RUN sudo mkdir -p /etc/easy-chat-pushjs/config
RUN sudo mkdir -p /etc/easy-chat-pushjs/scripts
RUN echo "Script has been successfully executed"

RUN git clone https://github.com/AdamSEY/easy-chat-pushjs /etc/easy-chat-pushjs/src
#entrypoint files
COPY scripts/* /etc/easy-chat-pushjs/scripts/
RUN chmod +x /etc/easy-chat-pushjs/scripts/*.sh



# config files
COPY $jwt_public_key /etc/easy-chat-pushjs/config/jwtRS256.key.pub
COPY $firebase_sdk_admin_json /etc/easy-chat-pushjs/config/firebase_admin_sdk.json

WORKDIR /etc/easy-chat-pushjs/src
ENTRYPOINT ["/etc/easy-chat-pushjs/scripts/entrypoint.sh"]

EXPOSE 5511:5511